<?php

use App\Constants\Types;

return[

    "PENDING_STATUS"        => Types::PENDING_STATUS,
    "RESERVED_STATUS"       => Types::RESERVED_STATUS,
    "REJECTED_STATUS"       => Types::REJECTED_STATUS,
    "'PARTIALLY_PAID_STATUS"   => Types::PARTIALLY_PAID_STATUS,
    "COMPLETED_STATUS"      => Types::COMPLETED_STATUS,
    "RESCHEDULED_STATUS"    => Types::RESCHEDULED_STATUS,
    "CANCELLED_STATUS"      => Types::CANCELLED_STATUS,

];